packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.27.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  tsup: ^8.5.0
  react: 19.0.0
  react-dom: 19.0.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  react-hook-form: '^7.56.4'
  '@hookform/resolvers': '^5.0.1'
  '@eslint/js': '^9.30.0'
  pino-http: ^10.5.0
  pino-nestjs: ^0.1.3
  '@nestjs/config': ^4.0.2
  '@nestjs/throttler': ^6.4.0
  helmet: ^8.1.0
  '@nestjs/common': ^11.1.3
  '@nestjs/swagger': ^11.2.0
  zod: ^3.25.74
