/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as _pathlessLayoutRouteRouteImport } from './routes/__pathlessLayout/route'
import { Route as _pathlessLayoutTransactionsRouteImport } from './routes/__pathlessLayout/transactions'
import { Route as _pathlessLayoutPlanRouteImport } from './routes/__pathlessLayout/plan'
import { Route as _pathlessLayoutMembersRouteImport } from './routes/__pathlessLayout/members'
import { Route as _pathlessLayoutAnalyticsRouteImport } from './routes/__pathlessLayout/analytics'
import { Route as _pathlessLayoutAccountsRouteImport } from './routes/__pathlessLayout/accounts'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const _pathlessLayoutRouteRoute = _pathlessLayoutRouteRouteImport.update({
  id: '/__pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _pathlessLayoutTransactionsRoute =
  _pathlessLayoutTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => _pathlessLayoutRouteRoute,
  } as any)
const _pathlessLayoutPlanRoute = _pathlessLayoutPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any)
const _pathlessLayoutMembersRoute = _pathlessLayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any)
const _pathlessLayoutAnalyticsRoute =
  _pathlessLayoutAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => _pathlessLayoutRouteRoute,
  } as any)
const _pathlessLayoutAccountsRoute = _pathlessLayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/accounts': typeof _pathlessLayoutAccountsRoute
  '/analytics': typeof _pathlessLayoutAnalyticsRoute
  '/members': typeof _pathlessLayoutMembersRoute
  '/plan': typeof _pathlessLayoutPlanRoute
  '/transactions': typeof _pathlessLayoutTransactionsRoute
}
export interface FileRoutesByTo {
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/accounts': typeof _pathlessLayoutAccountsRoute
  '/analytics': typeof _pathlessLayoutAnalyticsRoute
  '/members': typeof _pathlessLayoutMembersRoute
  '/plan': typeof _pathlessLayoutPlanRoute
  '/transactions': typeof _pathlessLayoutTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__pathlessLayout': typeof _pathlessLayoutRouteRouteWithChildren
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/__pathlessLayout/accounts': typeof _pathlessLayoutAccountsRoute
  '/__pathlessLayout/analytics': typeof _pathlessLayoutAnalyticsRoute
  '/__pathlessLayout/members': typeof _pathlessLayoutMembersRoute
  '/__pathlessLayout/plan': typeof _pathlessLayoutPlanRoute
  '/__pathlessLayout/transactions': typeof _pathlessLayoutTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/invites'
    | '/login'
    | '/setup'
    | '/accounts'
    | '/analytics'
    | '/members'
    | '/plan'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invites'
    | '/login'
    | '/setup'
    | '/accounts'
    | '/analytics'
    | '/members'
    | '/plan'
    | '/transactions'
  id:
    | '__root__'
    | '/__pathlessLayout'
    | '/invites'
    | '/login'
    | '/setup'
    | '/__pathlessLayout/accounts'
    | '/__pathlessLayout/analytics'
    | '/__pathlessLayout/members'
    | '/__pathlessLayout/plan'
    | '/__pathlessLayout/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _pathlessLayoutRouteRoute: typeof _pathlessLayoutRouteRouteWithChildren
  InvitesRoute: typeof InvitesRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__pathlessLayout': {
      id: '/__pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _pathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__pathlessLayout/transactions': {
      id: '/__pathlessLayout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof _pathlessLayoutTransactionsRouteImport
      parentRoute: typeof _pathlessLayoutRouteRoute
    }
    '/__pathlessLayout/plan': {
      id: '/__pathlessLayout/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof _pathlessLayoutPlanRouteImport
      parentRoute: typeof _pathlessLayoutRouteRoute
    }
    '/__pathlessLayout/members': {
      id: '/__pathlessLayout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof _pathlessLayoutMembersRouteImport
      parentRoute: typeof _pathlessLayoutRouteRoute
    }
    '/__pathlessLayout/analytics': {
      id: '/__pathlessLayout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof _pathlessLayoutAnalyticsRouteImport
      parentRoute: typeof _pathlessLayoutRouteRoute
    }
    '/__pathlessLayout/accounts': {
      id: '/__pathlessLayout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof _pathlessLayoutAccountsRouteImport
      parentRoute: typeof _pathlessLayoutRouteRoute
    }
  }
}

interface _pathlessLayoutRouteRouteChildren {
  _pathlessLayoutAccountsRoute: typeof _pathlessLayoutAccountsRoute
  _pathlessLayoutAnalyticsRoute: typeof _pathlessLayoutAnalyticsRoute
  _pathlessLayoutMembersRoute: typeof _pathlessLayoutMembersRoute
  _pathlessLayoutPlanRoute: typeof _pathlessLayoutPlanRoute
  _pathlessLayoutTransactionsRoute: typeof _pathlessLayoutTransactionsRoute
}

const _pathlessLayoutRouteRouteChildren: _pathlessLayoutRouteRouteChildren = {
  _pathlessLayoutAccountsRoute: _pathlessLayoutAccountsRoute,
  _pathlessLayoutAnalyticsRoute: _pathlessLayoutAnalyticsRoute,
  _pathlessLayoutMembersRoute: _pathlessLayoutMembersRoute,
  _pathlessLayoutPlanRoute: _pathlessLayoutPlanRoute,
  _pathlessLayoutTransactionsRoute: _pathlessLayoutTransactionsRoute,
}

const _pathlessLayoutRouteRouteWithChildren =
  _pathlessLayoutRouteRoute._addFileChildren(_pathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _pathlessLayoutRouteRoute: _pathlessLayoutRouteRouteWithChildren,
  InvitesRoute: InvitesRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
