export const CURRENCIES = [
  {code: 'RSD', name: 'Serbian Dinar (RSD)'},
  {code: 'USD', name: 'US Dollar ($)'},
  {code: 'EUR', name: 'Euro (€)'},
  {code: 'GBP', name: 'British Pound (£)'},
  {code: 'JPY', name: 'Japanese Yen (¥)'},
  {code: 'CAD', name: 'Canadian Dollar (C$)'},
  {code: 'AUD', name: 'Australian Dollar (A$)'},
  {code: 'CHF', name: 'Swiss Franc (CHF)'},
  {code: 'CNY', name: 'Chinese Yuan (¥)'},
  {code: 'INR', name: 'Indian Rupee (₹)'},
  {code: 'BRL', name: 'Brazilian Real (R$)'},
  {code: 'RUB', name: 'Russian Ruble (₽)'},
  {code: 'KRW', name: 'South Korean Won (₩)'},
  {code: 'MXN', name: 'Mexican Peso (MX$)'},
  {code: 'SEK', name: 'Swedish Krona (kr)'},
  {code: 'NOK', name: 'Norwegian Krone (kr)'},
  {code: 'DKK', name: 'Danish Krone (kr)'},
  {code: 'NZD', name: 'New Zealand Dollar (NZ$)'},
  {code: 'SGD', name: 'Singapore Dollar (S$)'},
  {code: 'HKD', name: 'Hong Kong Dollar (HK$)'},
  {code: 'ZAR', name: 'South African Rand (R)'},
];
