export const CURRENCIES = [
  {code: 'RSD', name: 'Srpski dinar (RSD)'},
  {code: 'USD', name: 'Američki dolar ($)'},
  {code: 'EUR', name: 'Evro (€)'},
  {code: 'GBP', name: 'Britanska funta (£)'},
  {code: 'JPY', name: 'Japanski jen (¥)'},
  {code: 'CAD', name: 'Kanadski dolar (C$)'},
  {code: 'AUD', name: 'Australijski dolar (A$)'},
  {code: 'CHF', name: 'Švajcarski franak (CHF)'},
  {code: 'CNY', name: 'Kineski juan (¥)'},
  {code: 'INR', name: 'Indijska rupija (₹)'},
  {code: 'BRL', name: 'Brazilski real (R$)'},
  {code: 'RUB', name: 'Ruska rublja (₽)'},
  {code: 'KRW', name: 'Južnokorejski von (₩)'},
  {code: 'MXN', name: 'Meksički pezo (MX$)'},
  {code: 'SEK', name: 'Švedska kruna (kr)'},
  {code: 'NOK', name: 'Norveška kruna (kr)'},
  {code: 'DKK', name: 'Danska kruna (kr)'},
  {code: 'NZD', name: 'Novozelandski dolar (NZ$)'},
  {code: 'SGD', name: 'Singapurski dolar (S$)'},
  {code: 'HKD', name: 'Hongkonški dolar (HK$)'},
  {code: 'ZAR', name: 'Južnoafrički rand (R)'},
];
