name: CD - Docker Hub Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ostdev/nest-wise

permissions:
  contents: read
jobs:
  build-and-push:
    name: Build and push (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: web
            dockerfile: apps/web/Dockerfile
          - service: core-api
            dockerfile: apps/core-api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          SHA_SHORT="${GITHUB_SHA::7}"
          TAGS=("${DOCKER_IMAGE}:${{ matrix.service }}-${SHA_SHORT}")

          if [ "${GITHUB_REF_NAME}" = "${{ github.event.repository.default_branch }}" ]; then
            TAGS+=("${DOCKER_IMAGE}:${{ matrix.service }}-latest")
          fi

          printf '%s\n' "tags=$(IFS=, ; echo "${TAGS[*]}")" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: |
            API_URL=https://api.nestwise.finance
            POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}
            POSTHOG_HOST=${{ secrets.POSTHOG_HOST }}

      - name: Show published tags
        run: |
          echo "Published: ${{ steps.meta.outputs.tags }}"
