name: Playwright E2E Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.12.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        working-directory: apps/web
        run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/web
        run: pnpm e2e:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
